name: Delete branch after merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch-after-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.event.pull_request.merged == true
      - uses: ministryofjustice/github-actions/branch-deleter@master
        if: github.event.pull_request.merged == true
        env:
          github-token: ${{ secrets.GIT_TOKEN }}
