name: on pull request merge, delete the branch

on:
  pull_request

jobs:
  delete-branch-after-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          NO_BRANCH_DELETED_EXIT_CODE: 0
