name: on pull request merge, delete the branch

on:
  pull_request

jobs:
  delete-branch-after-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: SvanBoxel/delete-merged-branch@master
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
